### ISSUE TITLE
Got Error when run demo WDL in AWS Batch

### ISSUE THREAD

**Issue by MMichael-S** [wleepang/demo-genomics-workflow-wdl#1]
Hi

When I run the following command
curl -X POST "http://localhost:8000/api/workflows/v1" \
    -H  "accept: application/json" \
    -F "workflowSource=@main.wdl" \
    -F "workflowInputs=@inputs.json"

I got some error msg from AWS Batch job log. Is there a problem with my submitted job? Or some other reason?
Thank you.

2021-01-25 16:48:58,163 cromwell-system-akka.dispatchers.api-dispatcher-654 INFO  - Unspecified type (Unspecified version) workflow 1ccf29a5-c2e6-441d-8cbd-ca369618a7cb submitted
--
2021-01-25 16:49:00,143 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - 1 new workflows fetched by cromid-7a2526f: 1ccf29a5-c2e6-441d-8cbd-ca369618a7cb
2021-01-25 16:49:00,143 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - WorkflowManagerActor Starting workflow UUID(1ccf29a5-c2e6-441d-8cbd-ca369618a7cb)
2021-01-25 16:49:00,144 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - WorkflowManagerActor Successfully started WorkflowActor-1ccf29a5-c2e6-441d-8cbd-ca369618a7cb
2021-01-25 16:49:00,144 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2021-01-25 16:49:00,152 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - MaterializeWorkflowDescriptorActor [UUID(1ccf29a5)]: Parsing workflow as WDL 1.0
2021-01-25 16:49:00,444 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - MaterializeWorkflowDescriptorActor [UUID(1ccf29a5)]: Call-to-Backend assignments: simple_variant_call.samtools_index -> AWSBATCH, simple_variant_call.bcftools_call -> AWSBATCH, simple_variant_call.bwa_mem -> AWSBATCH, simple_variant_call.samtools_sort -> AWSBATCH, simple_variant_call.bcftools_mpileup -> AWSBATCH
2021-01-25 16:49:00,449  WARN  - Unrecognized configuration key(s) for AwsBatch: auth, numCreateDefinitionAttempts, filesystems.s3.duplication-strategy, numSubmitAttempts, default-runtime-attributes.scriptBucketName
2021-01-25 16:49:03,605 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - WorkflowExecutionActor-1ccf29a5-c2e6-441d-8cbd-ca369618a7cb [UUID(1ccf29a5)]: Starting simple_variant_call.bwa_mem
2021-01-25 16:49:04,305 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - Assigned new job execution tokens to the following groups: 1ccf29a5: 1
2021-01-25 16:49:04,652 cromwell-system-akka.dispatchers.engine-dispatcher-25 INFO  - 1ccf29a5-c2e6-441d-8cbd-ca369618a7cb-EngineJobExecutionActor-simple_variant_call.bwa_mem:NA:1 [UUID(1ccf29a5)]: Could not copy a suitable cache hit for 1ccf29a5:simple_variant_call.bwa_mem:-1:1. No copy attempts were made.
2021-01-25 16:49:04,664 cromwell-system-akka.dispatchers.engine-dispatcher-25 ERROR - Failed to hash "${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz": java.lang.IllegalArgumentException: Could not build the path "${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Failures:
s3: ${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz does not have a s3 scheme (IllegalArgumentException) Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems
2021-01-25 16:49:04,664 cromwell-system-akka.dispatchers.engine-dispatcher-9 ERROR - 1ccf29a5:simple_variant_call.bwa_mem:-1:1: Hash error (java.lang.IllegalArgumentException: Could not build the path "${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz". It may refer to a filesystem not supported by this instance of Cromwell. Supported filesystems are: s3. Failures:
s3: ${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz does not have a s3 scheme (IllegalArgumentException) Please refer to the documentation for more information on how to configure filesystems: http://cromwell.readthedocs.io/en/develop/backends/HPC/#filesystems), disabling call caching for this job.
2021-01-25 16:49:04,876 cromwell-system-akka.dispatchers.backend-dispatcher-9437 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: `bwa mem -t 16 \    /cromwell_root/broad-references/hg38/v0/Homo_sapiens_assembly38.fasta \    ${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz ${input_prefix}/${sample_id}_R2_trim_samp-0p1.fastq.gz \    > NIST7035.sam`
2021-01-25 16:49:05,254 cromwell-system-akka.dispatchers.backend-dispatcher-9437 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: `bwa mem -t 16 \    /cromwell_root/broad-references/hg38/v0/Homo_sapiens_assembly38.fasta \    ${input_prefix}/${sample_id}_R1_trim_samp-0p1.fastq.gz ${input_prefix}/${sample_id}_R2_trim_samp-0p1.fastq.gz \    > NIST7035.sam`
2021-01-25 16:49:05,724  INFO  - Submitting taskId: simple_variant_call.bwa_mem-None-1, job definition : arn:aws:batch:us-east-1:861504766936:job-definition/cromwell_biocontainers_bwa_v0_7_15_cv4edd067312296db821e51892f9cba03bc4b9e553e:1, script: s3://cromwell-genomics-shifei/scripts/2685a9756913b1c3557483ed1452e6d0
2021-01-25 16:49:07,097 cromwell-system-akka.dispatchers.backend-dispatcher-9437 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: job id: 8e02a833-3852-4a60-b61f-07d90404ab60
2021-01-25 16:49:07,101 cromwell-system-akka.dispatchers.backend-dispatcher-9438 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: Status change from - to Initializing
2021-01-25 16:51:45,914 cromwell-system-akka.dispatchers.backend-dispatcher-9462 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: Status change from Initializing to Running
2021-01-25 16:52:46,375 cromwell-system-akka.dispatchers.backend-dispatcher-9473 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: Having to fall back to AWS query for status
2021-01-25 16:52:46,701 cromwell-system-akka.dispatchers.backend-dispatcher-9473 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(1ccf29a5)simple_variant_call.bwa_mem:NA:1]: Status change from Running to Failed
2021-01-25 16:52:47,919 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - WorkflowManagerActor Workflow 1ccf29a5-c2e6-441d-8cbd-ca369618a7cb failed (during ExecutingWorkflowState): cromwell.engine.io.IoAttempts$EnhancedCromwellIoException: [Attempted 1 time(s)] - IOException: Could not read from s3://cromwell-genomics-shifei/cromwell-execution/simple_variant_call/1ccf29a5-c2e6-441d-8cbd-ca369618a7cb/call-bwa_mem/bwa_mem-rc.txt: s3://s3.amazonaws.com/cromwell-genomics-shifei/cromwell-execution/simple_variant_call/1ccf29a5-c2e6-441d-8cbd-ca369618a7cb/call-bwa_mem/bwa_mem-rc.txt
Caused by: java.io.IOException: Could not read from s3://cromwell-genomics-shifei/cromwell-execution/simple_variant_call/1ccf29a5-c2e6-441d-8cbd-ca369618a7cb/call-bwa_mem/bwa_mem-rc.txt: s3://s3.amazonaws.com/cromwell-genomics-shifei/cromwell-execution/simple_variant_call/1ccf29a5-c2e6-441d-8cbd-ca369618a7cb/call-bwa_mem/bwa_mem-rc.txt	at cromwell.core.path.EvenBetterPathMethods$$anonfun$fileIoErrorPf$1.applyOrElse(EvenBetterPathMethods.scala:117)	at cromwell.core.path.EvenBetterPathMethods$$anonfun$fileIoErrorPf$1.applyOrElse(EvenBetterPathMethods.scala:116)	at map @ cromwell.engine.io.nio.NioFlow.handleSingleCommand(NioFlow.scala:68)	at map @ cromwell.engine.io.nio.NioFlow.$anonfun$processCommand$5(NioFlow.scala:54)	at flatMap @ cromwell.engine.io.nio.NioFlow.$anonfun$processCommand$1(NioFlow.scala:53)
Caused by: java.nio.file.NoSuchFileException: s3://s3.amazonaws.com/cromwell-genomics-shifei/cromwell-execution/simple_variant_call/1ccf29a5-c2e6-441d-8cbd-ca369618a7cb/call-bwa_mem/bwa_mem-rc.txt	at org.lerch.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:354)	at java.base/java.nio.file.Files.newInputStream(Files.java:155)	at better.files.File.newInputStream(File.scala:455)	at cromwell.core.path.BetterFileMethods.newInputStream(BetterFileMethods.scala:249)	at cromwell.core.path.BetterFileMethods.newInputStream$(BetterFileMethods.scala:248)	at cromwell.filesystems.s3.S3Path.newInputStream(S3PathBuilder.scala:157)	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream(EvenBetterPathMethods.scala:97)	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream$(EvenBetterPathMethods.scala:94)	at cromwell.filesystems.s3.S3Path.mediaInputStream(S3PathBuilder.scala:157)	at cromwell.core.path.EvenBetterPathMethods.$anonfun$withBufferedStream$1(EvenBetterPathMethods.scala:135)	at cromwell.util.TryWithResource$.$anonfun$tryWithResource$1(TryWithResource.scala:14)	at scala.util.Try$.apply(Try.scala:213)	at cromwell.util.TryWithResource$.tryWithResource(TryWithResource.scala:10)	at cromwell.core.path.EvenBetterPathMethods.withBufferedStream(EvenBetterPathMethods.scala:135)	at cromwell.core.path.EvenBetterPathMethods.withBufferedStream$(EvenBetterPathMethods.scala:134)	at cromwell.filesystems.s3.S3Path.withBufferedStream(S3PathBuilder.scala:157)	at cromwell.core.path.EvenBetterPathMethods.limitFileContent(EvenBetterPathMethods.scala:142)	at cromwell.core.path.EvenBetterPathMethods.limitFileContent$(EvenBetterPathMethods.scala:142)	at cromwell.filesystems.s3.S3Path.limitFileContent(S3PathBuilder.scala:157)	at cromwell.engine.io.nio.NioFlow.$anonfun$readAsString$1(NioFlow.scala:100)	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2021-01-25 16:52:47,919 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - WorkflowManagerActor WorkflowActor-1ccf29a5-c2e6-441d-8cbd-ca369618a7cb is in a terminal state: WorkflowFailedState

**Comment by wleepang** [comment]
Do you have the log from the failed task in the workflow?

**Comment by wleepang** [comment]
If you ran this with the `inputs.json` provided, there was an error there with the list of FASTQs. There were interpolated values in the `inputs.json` which are not handled.

The workflow should be able to run on its own without an inputs file.
